# ---------------------------------------------------------------------------- #
#                            Development Dockerfile                            #
# ---------------------------------------------------------------------------- #

FROM node:latest

WORKDIR /app

COPY . .

# Nodemon for hot reloads
RUN npm install --save-dev nodemon

EXPOSE 3000

ENV NODE_ENV=development
ENV PORT=3000

CMD ["sh", "-c", "npm install && npx nodemon index.js"]
